// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZrZe1gQzJ6wG_SrWrZvGCIfcFJlMKqkc',
    appId: '1:1015010025725:web:350dbdd31f374c89c11e94',
    messagingSenderId: '1015010025725',
    projectId: 'flutter-chat-e4f96',
    authDomain: 'flutter-chat-e4f96.firebaseapp.com',
    storageBucket: 'flutter-chat-e4f96.firebasestorage.app',
    measurementId: 'G-8RJXF4CQJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMo9uxhVqbes001xQ1CqgbYvopfMAkjIk',
    appId: '1:1015010025725:android:84e95f0c6ab58125c11e94',
    messagingSenderId: '1015010025725',
    projectId: 'flutter-chat-e4f96',
    storageBucket: 'flutter-chat-e4f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgfaC4wTWdYBrseo5nM6vWaeakPBWg48',
    appId: '1:1015010025725:ios:471f4a2ec6202c8dc11e94',
    messagingSenderId: '1015010025725',
    projectId: 'flutter-chat-e4f96',
    storageBucket: 'flutter-chat-e4f96.firebasestorage.app',
    iosBundleId: 'com.example.seniorsCompanionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgfaC4wTWdYBrseo5nM6vWaeakPBWg48',
    appId: '1:1015010025725:ios:471f4a2ec6202c8dc11e94',
    messagingSenderId: '1015010025725',
    projectId: 'flutter-chat-e4f96',
    storageBucket: 'flutter-chat-e4f96.firebasestorage.app',
    iosBundleId: 'com.example.seniorsCompanionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZrZe1gQzJ6wG_SrWrZvGCIfcFJlMKqkc',
    appId: '1:1015010025725:web:b8d84622e65b9b4fc11e94',
    messagingSenderId: '1015010025725',
    projectId: 'flutter-chat-e4f96',
    authDomain: 'flutter-chat-e4f96.firebaseapp.com',
    storageBucket: 'flutter-chat-e4f96.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAZrZe1gQzJ6wG_SrWrZvGCIfcFJlMKqkc',
    appId: '1:1015010025725:web:350dbdd31f374c89c11e94',
    messagingSenderId: '1015010025725',
    projectId: 'flutter-chat-e4f96',
    authDomain: 'flutter-chat-e4f96.firebaseapp.com',
    storageBucket: 'flutter-chat-e4f96.firebasestorage.app',
  );

}